/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SourceDataRouteImport } from './routes/source-data'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as IntegrationHubRouteImport } from './routes/integration-hub'
import { Route as GenieRouteImport } from './routes/genie'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminIntegrationsRouteImport } from './routes/admin-integrations'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceDataRoute = SourceDataRouteImport.update({
  id: '/source-data',
  path: '/source-data',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationHubRoute = IntegrationHubRouteImport.update({
  id: '/integration-hub',
  path: '/integration-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const GenieRoute = GenieRouteImport.update({
  id: '/genie',
  path: '/genie',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/admin-integrations',
  path: '/admin-integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-integrations': typeof AdminIntegrationsRoute
  '/alerts': typeof AlertsRoute
  '/devices': typeof DevicesRoute
  '/family': typeof FamilyRoute
  '/genie': typeof GenieRoute
  '/integration-hub': typeof IntegrationHubRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/source-data': typeof SourceDataRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-integrations': typeof AdminIntegrationsRoute
  '/alerts': typeof AlertsRoute
  '/devices': typeof DevicesRoute
  '/family': typeof FamilyRoute
  '/genie': typeof GenieRoute
  '/integration-hub': typeof IntegrationHubRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/source-data': typeof SourceDataRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-integrations': typeof AdminIntegrationsRoute
  '/alerts': typeof AlertsRoute
  '/devices': typeof DevicesRoute
  '/family': typeof FamilyRoute
  '/genie': typeof GenieRoute
  '/integration-hub': typeof IntegrationHubRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/source-data': typeof SourceDataRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-integrations'
    | '/alerts'
    | '/devices'
    | '/family'
    | '/genie'
    | '/integration-hub'
    | '/reports'
    | '/settings'
    | '/source-data'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-integrations'
    | '/alerts'
    | '/devices'
    | '/family'
    | '/genie'
    | '/integration-hub'
    | '/reports'
    | '/settings'
    | '/source-data'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/admin-integrations'
    | '/alerts'
    | '/devices'
    | '/family'
    | '/genie'
    | '/integration-hub'
    | '/reports'
    | '/settings'
    | '/source-data'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AlertsRoute: typeof AlertsRoute
  DevicesRoute: typeof DevicesRoute
  FamilyRoute: typeof FamilyRoute
  GenieRoute: typeof GenieRoute
  IntegrationHubRoute: typeof IntegrationHubRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SourceDataRoute: typeof SourceDataRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source-data': {
      id: '/source-data'
      path: '/source-data'
      fullPath: '/source-data'
      preLoaderRoute: typeof SourceDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration-hub': {
      id: '/integration-hub'
      path: '/integration-hub'
      fullPath: '/integration-hub'
      preLoaderRoute: typeof IntegrationHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genie': {
      id: '/genie'
      path: '/genie'
      fullPath: '/genie'
      preLoaderRoute: typeof GenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-integrations': {
      id: '/admin-integrations'
      path: '/admin-integrations'
      fullPath: '/admin-integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AlertsRoute: AlertsRoute,
  DevicesRoute: DevicesRoute,
  FamilyRoute: FamilyRoute,
  GenieRoute: GenieRoute,
  IntegrationHubRoute: IntegrationHubRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SourceDataRoute: SourceDataRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
